---
title: "Corona Virus Report"
author:
- familyname: XXXX
  othernames: XXX
  address: Monash Universtidy
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
- familyname: XXXX
  othernames: Reports
  address: XXX
  qualifications: XXX
- familyname: XXX
  othernames: XXX
  address: XXX
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: true
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
library(readr)
library(ggplot2)

```


```{r}
tut9dat <- read_csv("Data/Data_Tables_Criminal_Incidents_Visualisation_Year_Ending_December_2019.csv")
```


# Section 1

Select one offence from the data set and explain how has the offence changed over time?

```{r}
tut9partdat <- tut9dat %>%
  filter(`Offence Division` == "C Drug offences")

```

```{r offtable, fig.cap= "C drug offences"}
table <- tut9partdat %>%
  dplyr::select( Year, 
                `Offence Division`,
                `Incidents Recorded`,
               ) 

knitr::kable(
table[1:5,], booktabs = TRUE,
  caption = 'Table with first five rows') %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))
```

In the table \@ref(tab:offtable) we have displayed the top five rows 

```{r offfig, fig.asp="Incidents Recorded for drug offences"}
ggplot(data = tut9partdat, mapping =  aes(x = Year, y = `Incidents Recorded`)) + geom_point()
```

In the fig \@ref(fig:offfig) we can see the incidents recorded for drug

# Citation examples


 @BC64 and this is another article about COVID and I can also cite R packages as





